name: 林海雪原
#markdown: rdiscount
#rdiscount:
#  extensions:
#    - autolink
#    - footnotes
#    - smart
baseurl: /jekyll
#highlighter: pygments

mermaid:
  src: '/js/mermaid.js'
  src_config: '/js/mermaid_config.js'