name: 林海雪原
#markdown: rdiscount
#rdiscount:
#  extensions:
#    - autolink
#    - footnotes
#    - smart
baseurl: /jekyll
#highlighter: pygments

gems: [jekyll-mermaid]
mermaid:
  src: 'https://cdn.rawgit.com/knsv/mermaid/0.5.1/dist/mermaid.js'